FROM nginx:stable-alpine AS production-stage
COPY .next /var/www/html/prod

### nginx setting
# RUN rm -rf /etc/nginx/conf.d/default.conf
COPY deploy-config/nginx.conf /etc/nginx/nginx.conf
COPY deploy-config/conf.d/default.conf /etc/nginx/conf.d/default.conf
# RUN ln -s /etc/nginx/sites-available /etc/nginx/sites-enabled

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]

# ENTRYPOINT ["npm", "start"]
